<?php
$labels = array();
$labels['pictures'] = 'Fotos';

$labels['home'] = "Start";
$labels['create'] = "Erstellen";
$labels['page'] = "Seite";
$labels['all'] = "Alle";
$labels['noimages'] = "Bis jetzt keine Bilder vorhanden";
$labels['edit'] = "Bearbeiten";
$labels['album'] = "Album";
$labels['new_album'] = "Neues Album";
$labels['rename'] = "Umbenennen";
$labels['move'] = "Verschieben";
$labels['move_image'] = "Bild verschieben";
$labels['delete'] = "Löschen";

$labels['exif_undefined'] = "Undefiniert";
$labels['exif_manual'] = "Manuell";
$labels['exif_time_auto'] = "Zeitautomatik";
$labels['exif_exposure_auto'] = "Belichtungsautomatik";
$labels['exif_shutter_auto'] = "Blendenautomatik";
$labels['exif_creative_auto'] = "Kreativ (Langsam)";
$labels['exif_action_auto'] = "Action (High speed)";
$labels['exif_portrait_auto'] = "Portrait";
$labels['exif_landscape_auto'] = "Landschaft";
$labels['exif_bulb'] = "Bulb";

$labels['exif_unkown'] = "Unknown";
$labels['exif_average'] = "Average";
$labels['exif_middle'] = "Mittenbetont";
$labels['exif_spot'] = "Spot";
$labels['exif_multi-spot'] = "Multi-Spot";
$labels['exif_multi'] = "Mehrfeldmessung";
$labels['exif_partial'] = "Partial";
$labels['exif_other'] = "Anderer";

$labels['exif_camera'] = "Kamera";
$labels['exif_focalength'] = "Brennweite";
$labels['exif_fstop'] = "F-Stopp";
$labels['exif_ISO'] = "ISO";
$labels['exif_date'] = "Datum";
$labels['exif_desc'] = "Beschreibung";
$labels['exif_sw'] = "Software";
$labels['exif_expos'] = "Belichtung";
$labels['exif_flash'] = "Blitz";
$labels['exif_meter'] = "Belichtungsmessung";
$labels['exif_whiteb'] = "Weißabgleich";
$labels['exif_geo'] = "Auf Karte anzeigen";
?>