<?php
$labels = array();
$labels['pictures'] = 'Photos';

$labels['home'] = "Home"; // Name of home link in breadcrumb navigation
$labels['new'] = "New"; // Text to display for new images.
$labels['page'] = "Page"; // Text used for page navigation
$labels['all'] = "All"; // Text used for link to display all images in one page
$labels['noimages'] = "No images... yet !"; // Empty folder text
$labels['edit'] = "Edit";
$labels['album'] = "Album";
$labels['new_album'] = "New Album";
$labels['rename'] = "Rename";
$labels['move'] = "Move";
$labels['delete'] = "Delete";

$labels['exif_undefined'] = "Undefined";
$labels['exif_manual'] = "Manual";
$labels['exif_time_auto'] = "Auto Time";
$labels['exif_exposure_auto'] = "Auto Exposure";
$labels['exif_shutter_auto'] = "Auto Shutter";
$labels['exif_creative_auto'] = "Creative (Slow)";
$labels['exif_action_auto'] = "Action (High speed)";
$labels['exif_portrait_auto'] = "Portrait";
$labels['exif_landscape_auto'] = "Landscape";
$labels['exif_bulb'] = "Bulb";

$labels['exif_unkown'] = "Unknown";
$labels['exif_average'] = "Average";
$labels['exif_middle'] = "Center";
$labels['exif_spot'] = "Spot";
$labels['exif_multi-spot'] = "Multi-Spot";
$labels['exif_multi'] = "Multi-field";
$labels['exif_partial'] = "Partial";
$labels['exif_other'] = "Other";
?>