<?php
$labels = array();
$labels['pictures'] = 'Photos';

$labels['home'] = "Home";
$labels['create'] = "Create";
$labels['page'] = "Page";
$labels['all'] = "All";
$labels['noimages'] = "No images... yet !";
$labels['edit'] = "Edit";
$labels['album'] = "Album";
$labels['new_album'] = "New Album";
$labels['rename'] = "Rename";
$labels['move'] = "Move";
$labels['move_image'] = "Move picture";
$labels['delete'] = "Delete";
$labels['share'] = "Share";
$labels['upload'] = "Upload";
$labels['picdconfirm'] = "Do you want to delete the marked images (%c)?";
$labels['galdconfirm'] = "Do you want to delete the marked album?";
$labels['selalb'] = "Choose Album";
$labels['selshr'] = "New Share";
$labels['corpics'] = "There was an error processing your new pictures. The following pictures appear to be corrupted. Please fix or delete these images:";

$labels['exif_undefined'] = "Undefined";
$labels['exif_manual'] = "Manual";
$labels['exif_time_auto'] = "Auto Time";
$labels['exif_exposure_auto'] = "Auto Exposure";
$labels['exif_shutter_auto'] = "Auto Shutter";
$labels['exif_creative_auto'] = "Creative (Slow)";
$labels['exif_action_auto'] = "Action (High speed)";
$labels['exif_portrait_auto'] = "Portrait";
$labels['exif_landscape_auto'] = "Landscape";
$labels['exif_bulb'] = "Bulb";

$labels['exif_unkown'] = "Unknown";
$labels['exif_average'] = "Average";
$labels['exif_middle'] = "Center";
$labels['exif_spot'] = "Spot";
$labels['exif_multi-spot'] = "Multi-Spot";
$labels['exif_multi'] = "Multi-field";
$labels['exif_partial'] = "Partial";
$labels['exif_other'] = "Other";

$labels['exif_camera'] = "Camera";
$labels['exif_focalength'] = "Focal Length";
$labels['exif_fstop'] = "F-Stop";
$labels['exif_ISO'] = "ISO";
$labels['exif_date'] = "Date";
$labels['exif_desc'] = "Description";
$labels['exif_sw'] = "Software";
$labels['exif_expos'] = "Exposure";
$labels['exif_flash'] = "Flash";
$labels['exif_meter'] = "Metering Mode";
$labels['exif_whiteb'] = "Whitebalance";
$labels['exif_geo'] = "Show on map";
?>